version: "3"
services:
    csvserver:
        container_name: csv_appserver
        image: infracloudio/csvserver:latest
        volumes:
            - ./inputFile:/csvserver/inputdata
        environment:
            - CSVSERVER_BORDER=Orange
        ports:
            - "9393:9300"

