version: "3"
services:
    csvserver:
        container_name: csv_appserver
        image: infracloudio/csvserver:latest
        volumes:
            - ./inputFile:/csvserver/inputdata
        environment:
            - CSVSERVER_BORDER=Orange
        ports:
            - 9393:9300

    prometheus:
        container_name: csv__monitoringserver
        image: prom/prometheus:v2.22.0
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
              
