# My Prometheus global config

global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.


# A scrape configuration pointing to csv_appserver endpoint.

scrape_configs:

  - job_name: 'csv_appserver_metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['csv_appserver:9300']
